name: flutter_core_package
description: "A reusable Flutter core package with theme management, error handling, asset management, typography, dimensions, and state management with Riverpod."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0-333.2.beta
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

